export const USER_LOGIN = "USER_LOGIN"

/* incentive offer action start */
export const SAVE_OFFER = "SAVE_OFFER"
export const DELETE_OFFER = "DELETE_OFFER"
export const EDIT_OFFER = "EDIT_OFFER"
export const LIST_OFFERS = "LIST_OFFERS"

export class ListOffers {
    readonly type = LIST_OFFERS;
    constructor(public payload:any) {}
}
/* incentive offer action end */

/* ESIID LOOK UP CALL start */
export const ESIID_LOOK_UP = "ESIID_LOOK_UP"
/* ESIID LOOK UP CALL end */

/* Form upload start */
export const FORM_UPLOAD = "FORM_UPLOAD"
/* Form upload start */

/* Marketing agreement start */
export const SEARCH_MRKTG_AGREEMENT = "SEARCH_MRKTG_AGREEMENT"
export const UPDATE_MRKTG_AGREEMENT = "UPDATE_MRKTG_AGREEMENT"
export const DELETE_MRKTG_AGREEMENT = "DELETE_MRKTG_AGREEMENT"
export const CREATE_MRKTG_AGREEMENT = "CREATE_MRKTG_AGREEMENT"
export const UPDATE_MRKTG_AGREEMENT_STATUS = "UPDATE_MRKTG_AGREEMENT_STATUS"
export const SAVE_MRKTG_AGREEMENT = "SAVE_MRKTG_AGREEMENT"
export const SAVE_AGRM_FROM_ENTER_PAGE = "SAVE_AGRM_FROM_ENTER_PAGE"
export const SAVE_AGRM_FROM_PAY_PAGE = "SAVE_AGRM_FROM_PAY_PAGE"
export const GET_INFO_FOR_UPDATE_PAGE = "GET_INFO_FOR_UPDATE_PAGE"
/* Marketing agreement end */

/* Manage Contract start */
export const SEARCH_CONTRACT = "SEARCH_CONTRACT"
export const SAVE_CONTRACT_INFO = "SAVE_CONTRACT_INFO"
export const SAVE_CONTRACT_INFO_TODB = "SAVE_CONTRACT_INFO_TODB"
export const UPDATE_CONTRACT_INFO_TODB = "UPDATE_CONTRACT_INFO_TODB"
/* Manage Contract end */

/* Manage User start */
export const SEARCH_USERS = "SEARCH_USERS"
export const USER_DETAILS = "USER_DETAILS"
export const USER_UPDATE = "USER_UPDATE"
export const VIEW_ASSOCIATES = "VIEW_ASSOCIATES"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const EMPTY_RESET_PASSWORD = "EMPTY_RESET_PASSWORD"
export const REMOVE_USER = "REMOVE_USER"
export const DISASSOCIATE_CUST_FROM_USER = "DISASSOCIATE_CUST_FROM_USER"
export const SAVE_USER_DTLS_FOR_ASSOCIATE_MORE = "SAVE_USER_DTLS_FOR_ASSOCIATE_MORE"
export const SEARCH_BP_FOR_ASSC_MORE = "SEARCH_BP_FOR_ASSC_MORE"
export const ASSOCIATE_CUSTOMERS_TO_USER = "ASSOCIATE_CUSTOMERS_TO_USER"
export const CHANGE_ADMIN_FOR_ASSOCIATE = "CHANGE_ADMIN_FOR_ASSOCIATE"
/* Manage User end */

/* changing Associate admin for customer associate */
export const SAVE_DETAILS_FOR_CHANGING_ADMIN = "SAVE_DETAILS_FOR_CHANGING_ADMIN"
/* changing Associate admin for customer associate */

/* Add user start */
export const SAVE_SELECTION = "SAVE_SELECTION"
export const SAVE_USERINFO = "SAVE_USERINFO"
export const SAVE_USERINFO_TO_DB = "SAVE_USERINFO_TO_DB"
export const SAVE_USER_INFO_ON_VERIFYPAGE = "SAVE_USER_INFO_ON_VERIFYPAGE"
export const SEARCH_BP = "SEARCH_BP"
export const SEARCH_BROKERS = "SEARCH_BROKERS"
export const SEARCH_CUSTOMERS = "SEARCH_CUSTOMERS"
export const SEARCH_BROKER_ASSOCIATES = "SEARCH_BROKER_ASSOCIATES"
export const IS_SAPID_EXIST_IN_SYSTEM = "IS_SAPID_EXIST_IN_SYSTEM"
export const IS_USERNAME_EXIST_IN_SYSTEM = "IS_USERNAME_EXIST_IN_SYSTEM"
export const SAVE_CUSTOMER_LIST = "SAVE_CUSTOMER_LIST"
export const LIST_EMA_ASSOCIATES = "LIST_EMA_ASSOCIATES"
export const LIST_EMM_ASSOCIATES = "LIST_EMM_ASSOCIATES"
export const LIST_ADMIN_ASSOCIATES = "LIST_ADMIN_ASSOCIATES"
export const SAVE_SELECTED_ADMIN = "SAVE_SELECTED_ADMIN"
export const GET_SELECTED_ADMIN_CUSTOMERS = "GET_SELECTED_ADMIN_CUSTOMERS"
export const SAVE_CUST_LIST_FOR_ASSC_MORE = "SAVE_CUST_LIST_FOR_ASSC_MORE"
export const DELETE_CUST_LIST_FOR_ASSC_MORE = "DELETE_CUST_LIST_FOR_ASSC_MORE"
export const SAVE_BILLING_ACCESS_PRIV_FOR_CUST_ASSOCIATE = "SAVE_BILLING_ACCESS_PRIV_FOR_CUST_ASSOCIATE"
export const SAVE_STARTSTOP_ACCESS_PRIV_FOR_CUST_ASSOCIATE = "SAVE_STARTSTOP_ACCESS_PRIV_FOR_CUST_ASSOCIATE"
/* Add user end */
